config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'
  get 'user_documents/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user_sessions#new'

  resources :notifications, only: [:index, :show, :destroy]

  resources :users, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :events, only: [:index]
    resources :user_documents, only: [:index]
    resources :user_groups, only: [:index]
  end

  resources :user_sessions, only: [:create, :destroy]

  resources :message_boards do
    resources :posts, only: [:index, :show, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :groups, only: [:index, :show, :create, :destroy] do
      resources :members, only: [:index, :create, :update, :destroy]
      resources :events, only: [:new, :create, :destroy]
    end
    resources :documents, only: [:index, :new, :create, :destroy]
    resources :rates, only: [:index, :create]
    resources :reviews, only: [:index, :create]
  end

  resources :posts do
    resources :approvals, only: [:create, :destroy]
  end

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  get 'errors/access_denied'
  get 'errors/record_not_found'
end

app/models/approval.rb
class Approval < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :user, presence: true
  validates :post, presence: true
end

app/controllers/approvals_controller.rb
class ApprovalsController < ApplicationController
  before_action :find_post

  def create
    if not already_approved?
      @approval = @post.approvals.create(user: current_user)
      if @approval.save
        redirect_to message_board_posts_url(@post.message_board_id, anchor: @post.id)
      else
        flash[:error] = "Operazione non riuscita."
      end
    end
  end

  def destroy
    if already_approved?
      if not @post.approvals.where(user: current_user).destroy_all
        flash[:error] = "Operazione non riuscita."
      end
    end

    redirect_to message_board_posts_url(@post.message_board_id, anchor: @post.id)
  end

  private
    def find_post
      @post = Post.find(params[:post_id])
    end

    def already_approved?
      Approval.where(user_id: current_user.id, post_id: params[:post_id]).exists?
    end
  
end

app/helpers/approvals_helper.rb
module ApprovalsHelper
end

app/views/approvals/_approval.html.erb
<div class="container">
  <div class="row justify-content-center">
    <% if current_user.id != post.user_id %>

      <% if pre_approval %>
        <%= link_to post_approval_url(post.id, pre_approval),
                    method: :delete,
                    class: 'link-approval' do %>
          <i class="fas fa-thumbs-up"></i>
        <% end %>
      <% else %>
        <%= link_to post_approvals_url(post.id),
                    method: :post,
                    class: 'link-approval' do %>
          <i class="far fa-thumbs-up"></i>
        <% end %>
      <% end %>

    <% else %>
      <i class="fas fa-pen my-post">
      </i>
    <% end %>
  </div>
  <div class="row justify-content-center">
    <%= approvals_count %>
  </div>
</div>