config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'
  get 'user_documents/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user_sessions#new'

  resources :notifications, only: [:index, :show, :destroy]

  resources :users, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :events, only: [:index]
    resources :user_documents, only: [:index]
    resources :user_groups, only: [:index]
  end

  resources :user_sessions, only: [:create, :destroy]

  resources :message_boards do
    resources :posts, only: [:index, :show, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :groups, only: [:index, :show, :create, :destroy] do
      resources :members, only: [:index, :create, :update, :destroy]
      resources :events, only: [:new, :create, :destroy]
    end
    resources :documents, only: [:index, :new, :create, :destroy]
    resources :rates, only: [:index, :create]
    resources :reviews, only: [:index, :create]
  end

  resources :posts do
    resources :approvals, only: [:create, :destroy]
  end

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  get 'errors/access_denied'
  get 'errors/record_not_found'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :participants, dependent: :destroy

  validates :group, presence: true
  validates :user, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 300 }
  validates :appointment, presence: true
  validates :place, presence: true, length: { maximum: 100 }

  default_scope -> { order(appointment: :asc) }
  scope :find_next, -> { where('appointment > ?', DateTime.now.beginning_of_day) }
  scope :paginated, -> (page, entries) { paginate(page: page, per_page: 4, total_entries: entries)}

  validate :appointment_date

  private

    def appointment_date
      return if appointment.blank?

      if appointment <= DateTime.now.beginning_of_day
        errors.add(:appointment, "must be after today")
      end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource :message_board
  load_and_authorize_resource :group, through: :message_board

  def index

    # @id_events = Participant.where(user_id: current_user).select(:event_id)
    # @events = Event.where(:id => @id_events).paginated(params[:page], Event.where(:id => @id_events).size)

    @events = current_user.events.paginated(params[:page], current_user.events.size)

    @events.each do |event|
      event.group.message_board
    end
  end

  def create
    Event.transaction do
      Notification.transaction do

        begin 

          @event = @group.events.build(events_params)
          @event.save! 
          
          @event.participants.create(role: "creator", user_id: current_user.id)
          @group.users.each do |user|
            if user.id != current_user.id
              @event.participants.create(role: "member", user_id: user.id)

              Notification.create(recipient: user, 
                actor: current_user, 
                action: "ha creato un evento in un gruppo di cui fai parte.", 
                notifiable: @event)
            end
          end
            
          flash[:success] = "Evento creato!" 
        
        rescue ActiveRecord::RecordInvalid
          flash[:danger] = "Errore creazione evento"
        end
      end
    end
    redirect_to message_board_group_url(@message_board, @group)
  end

  def new
    @event = Event.new
  end

  def destroy
    Event.find(params[:id]).destroy ? flash[:success] = "Evento eliminato!"
                                    : flash[:danger] = "Errore eliminazione evento"
    
    @message_board = MessageBoard.find(params[:message_board_id])
    @group = Group.find(params[:group_id])
    redirect_to message_board_group_url(@message_board, @group)
  end

  private
    def events_params
      params.require(:event).permit(:name, :description, :appointment, :place)
                            .merge(:user_id => current_user.id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<li class="list-group-item" id="event-<%= event.id %>" >
  
  <div class="d-flex flex-row">
    <div>
      <h5> <%= event.name %> </h5>
    </div>
    <% if controller.controller_name == "groups" %>
      <div class="float-right ml-auto">
        <%@creators.each do |creator| %>
          <% if creator.event_id == event.id && creator.user_id == current_user.id %>
            <%= link_to message_board_group_event_url(@message_board, @group, event), method: :delete do %>
              <button type="button" class="btn btn-danger">Elimina</button>
            <% end %>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="float-right ml-auto">
        <%= link_to "Vai al gruppo", message_board_group_url(event.group.message_board, event.group), 
                    class: "btn btn-info" %> 
      </div>
    <% end %>
  </div> 
    
  <p class="event-details">
    <i class="fas fa-calendar-alt mr-2"></i>
    <%= event.appointment.to_formatted_s(:short) %>
  </p>
  <p class="event-details">
    <i class="fas fa-map-marker-alt mr-2"></i>
    <%= event.place %>
  </p>
  <p><%= event.description %> </p>

  <p class="text-muted"><%= time_ago_in_words(event.created_at) %> ago</p>

</li>

app/views/events/index.html.erb
<h1>Eventi</h1>

<% if @events.any? %>
  <ul class="events-all">
    <%= render @events %>
  </ul>
  <%#= will_paginate @events, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>
<% else %>
  <div class="row">
    <div class="col-xs-12 col-lg-8 offset-lg-2">
      <div class="card text-center">
        <div class="card-body">
          Non partecipi ancora a nessun evento.
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/new.html.erb
<h1><%= @group.name %></h1>

<div class="card event-form">
  <div class="card-body">
    <h5 class="card-title">Crea un nuovo evento</h5>
    <%= form_for [@message_board.id, @group.id, @event], url: message_board_group_events_url(@message_board, @group, @event) do |f| %>
      <%= render 'shared/errors', object: f.object %>
      
      <div class="form-group">
        <label for="event_name">Nome</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <label for="event_description">Descrizione</label>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <label for="event_appointment">Data di ritrovo</label>
        <%= f.datetime_field :appointment, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control' %>
      </div>

      <div class="form-group">
        <label for="event_place">Luogo di ritrovo</label>
        <%= f.text_field :place, class: 'form-control' %>
      </div>

      <%= f.hidden_field :role, :value => "role" %>
      <%= f.hidden_field :group_id, :value => @group.id %>
      <%= f.submit "Crea", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>