config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'
  get 'user_documents/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user_sessions#new'

  resources :notifications, only: [:index, :show, :destroy]

  resources :users, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :events, only: [:index]
    resources :user_documents, only: [:index]
    resources :user_groups, only: [:index]
  end

  resources :user_sessions, only: [:create, :destroy]

  resources :message_boards do
    resources :posts, only: [:index, :show, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :groups, only: [:index, :show, :create, :destroy] do
      resources :members, only: [:index, :create, :update, :destroy]
      resources :events, only: [:new, :create, :destroy]
    end
    resources :documents, only: [:index, :new, :create, :destroy]
    resources :rates, only: [:index, :create]
    resources :reviews, only: [:index, :create]
  end

  resources :posts do
    resources :approvals, only: [:create, :destroy]
  end

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  get 'errors/access_denied'
  get 'errors/record_not_found'
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :message_board
  belongs_to :user
  belongs_to :category

  has_one_attached :file

  validates :message_board, presence: true
  validates :user, presence: true
  validates :category, presence: true
  validates :name, presence: true, length: { maximum: 100 }
  validates :description, presence: true, length: { maximum: 300 }

  scope :with_eager_loaded_image, -> { eager_load(file_attachment: :blob) }
  scope :with_preloaded_image, -> { preload(file_attachment: :blob) }
  scope :pagination, -> (page, entries) { paginate(page: page, per_page: 5, total_entries: entries).with_preloaded_image }
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  load_and_authorize_resource :message_board
  before_action :load_documents, only: :index
  before_action :correct_user, only: :destroy
  
  def index
    @course = @message_board.course
    @documents.each do |document|
      document.file
    end
  end

  def new
    @course = @message_board.course
    @categories = Category.all
    @document = Document.new

    @errors = params[:errors]
  end

  def create
    @document = current_user.documents.build(documents_params)

    if @document.save
      flash[:success] = "Documento inserito!"

      redirect_to :controller => 'documents',
                  :action => 'index',
                  :message_board_id => params[:message_board_id]
    else
      flash[:danger] = "Documento non inserito!"

      redirect_to :controller => 'documents',
                  :action => 'new',
                  :message_board_id => params[:message_board_id],
                  :errors => @document.errors.full_messages
    end

  end

  def destroy
    @document.file.purge
    @document.destroy ? flash[:success] = "Documento eliminato!" : flash[:danger] = "Documento non eliminato!"

    redirect_to :controller => 'documents',
                :action => 'index',
                :message_board_id => params[:message_board_id]
  end

  private
    def documents_params
      params.require(:document).permit(:name, :description, :category_id, :message_board_id, :file)
    end

    def correct_user
      @document = current_user.documents.find_by(id: params[:id])

      if @document.nil?
        flash[:danger] = "Non puoi eliminare un documento caricato da un altro!"
        redirect_to request.referrer 
      end
    end

    def load_documents
      @documents = @message_board.documents.pagination(params[:page], @message_board.documents.size)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<li id="document-<%= document.id %>" class="document">
  <div class="card">

    <div class="card-body">
      <div class="d-flex flex-row">
        <div class="mr-auto p-2">
          <h5 class="card-title"><%= document.name %></h5>  
        </div>
      
        <% if current_page?(controller: 'user_documents', action: 'index') %>
          <div class="p-2">
            <%= link_to "Vai all'insegnamento", message_board_documents_url(document.message_board_id), 
                        class: "btn btn-info" %>          
          </div>
        <% else %>
          <% if document.file.attached? %>
            <div class="p-2">
              <%= link_to "Download", 
                  rails_blob_url(document.file, disposition: 'attachment'),
                  class: "btn btn-success" %>
            </div>
          <% end %>       

          <% if current_user.id == document.user_id %>
            <div class="p-2">
              <%= button_to "Elimina", message_board_document_url(document.message_board_id, document.id), 
                                      method: :delete, data: { confirm: "Vuoi eliminare il documento?" }, 
                                      class: "btn btn-danger" %>
            </div>
          <% end %>   
        <% end%> 
      </div>

      <div class="d-flex flex-row">
        <div class="mr-auto p-2">
          <p class="card-text"><%= document.description %></p>
        </div>
      </div>

      <% if current_page?(controller: 'user_documents', action: 'index') %>
        <div class="d-flex flex-row">
          <div class="mr-auto p-2">
            <b>Insegnamento:</b> <%= document.message_board.course.name %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="card-footer text-muted text-center">
      <%= time_ago_in_words(document.updated_at) %> ago
    </div>
    
  </div>
</li>

app/views/documents/index.html.erb
<h1><%= @course.name %></h1>
<%= render "message_boards/menu" %>

<div class="d-flex flex-row upload-button">
  <div class="ml-auto p-2">
    <%= link_to "Upload documento", 
                  new_message_board_document_url(@message_board.id),
                  class: "btn btn-info" %>
  </div>
</div>

<ul class="documents">
  <%= render @documents %>
</ul>

<%= will_paginate @documents, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/documents/new.html.erb
<h1><%= @course.name %></h1>
<%= render "message_boards/menu", :type => "documents" %>

<div class="card document-form">
  <div class="card-body">
    <h5 class="card-title">Pubblica un nuovo documento</h5>
    <%= form_for [@message_board, @document] do |f| %>
      
      <div class="form-group">
        <label for="document_name">Nome</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <label for="document_description">Descrizione</label>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.file_field :file, class: "form-control-file" %>
      </div>

      <div class="form-group">
        <label for="document_category_id">Scegli categoria:</label>
        <%= f.collection_select(:category_id, @categories, :id, :name) %>
      </div>

      <%= f.hidden_field :message_board_id, :value => @message_board.id %>
      <%= f.submit "Pubblica", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>