config/routes.rb
Rails.application.routes.draw do
  get 'user_groups/index'
  get 'user_documents/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user_sessions#new'

  resources :notifications, only: [:index, :show, :destroy]

  resources :users, only: [:show] do
    resources :courses, only: [:index, :show]
    resources :events, only: [:index]
    resources :user_documents, only: [:index]
    resources :user_groups, only: [:index]
  end

  resources :user_sessions, only: [:create, :destroy]

  resources :message_boards do
    resources :posts, only: [:index, :show, :create, :destroy] do
      resources :comments, only: [:create, :destroy]
    end
    resources :groups, only: [:index, :show, :create, :destroy] do
      resources :members, only: [:index, :create, :update, :destroy]
      resources :events, only: [:new, :create, :destroy]
    end
    resources :documents, only: [:index, :new, :create, :destroy]
    resources :rates, only: [:index, :create]
    resources :reviews, only: [:index, :create]
  end

  resources :posts do
    resources :approvals, only: [:create, :destroy]
  end

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in

  get 'errors/access_denied'
  get 'errors/record_not_found'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource :user
  load_and_authorize_resource :course, through: :user

  def index
    @courses = @courses.includes(:message_board).order(:credit)
    @courses.each do |course|
      course.message_board.id
    end
  end

  def show
    redirect_to message_board_posts_url(@course.message_board)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<li id="course-<%= course.id %>">
  <div class="card text-center" >
    <div class="card-body">
      <h5 class="card-title"><%= course.name %></h5>
      <p class="card-text">Crediti: <%= course.credit %></p>
      <p class="card-text">Professore: <%= course.professor %></p>
    </div>
    <div class="card-footer">
      <%= link_to 'Visualizza', user_course_url(current_user.id, course.id), class: 'card-link'%>
      <%= link_to 'Voti', message_board_rates_url(course.message_board.id), class: 'card-link'%>
      <%= link_to 'Opinioni', message_board_reviews_url(course.message_board.id), class: 'card-link'%>
    </div>
  </div>
</li>

app/views/courses/index.html.erb
<h1>Insegnamenti</h1>

<ul class="courses">
  <% if @courses.any? %>
    <%= render @courses %>
  <% else %>
    <div class="row">
      <div class="col-xs-12 col-lg-8 offset-lg-2">
        <div class="card text-center">
          <div class="card-body">
            Non hai ancora insegnamenti caricati.
          </div>
        </div>
      </div>
    </div>
  <% end %>
</ul>

app/views/courses/show.html.erb
<h1>Courses#show</h1>
<p>Find me in app/views/courses/show.html.erb</p>